# Generated by Django 5.2.4 on 2025-10-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loanApplication',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('mobil', models.IntegerField()),
                ('loan_type', models.CharField(choices=[('home', 'Home Loan'), ('personal', 'Personal Loan'), ('car', 'Car Loan'), ('business', 'Business Loan'), ('property', 'Loan Against Property')], max_length=30)),
                ('loan_amount', models.CharField(max_length=20)),
            ],
        ),
    ]
