# Generated by Django 5.2.4 on 2025-10-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='mobil',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='mobile',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
